# Generated by Django 5.1.3 on 2024-11-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="client",
        ),
        migrations.AddField(
            model_name="reservation",
            name="nom_client",
            field=models.CharField(default="Client inconnu", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservation",
            name="prix_total",
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name="Photo",
        ),
    ]
